### ISSUE TITLE
Record video & get access to data

### ISSUE THREAD

**Issue by timschr** [OTTOMATIC-IO/pyphantom#6]
I can connect to the camera (Phantom Veo410L) by camera.connect(), but in the get_single_frame.py I get
```
Traceback (most recent call last):
  File "get_single_frame.py", line 22, in <module>
    get_single_frame(take_number=0, frame_number=0)
  File "get_single_frame.py", line 15, in get_single_frame
    frame_index = int(camera.takes[take_number]["firstfr"]) + frame_number
  File "/home/tim/.local/lib/python3.8/site-packages/pyphantom/flex.py", line 458, in __getitem__
    raise IndexError
IndexError
```
since camera.takes is empty. How can I start a recording using the pyphantom framework? 
I found the toggle() function in flex.py, which makes the cameras red led blink. When I now execute get_frames(), I get the error: 
`CameraError: Cinemag not ready`
So how can I get frames from the camera?

**Comment by NhatMinh26** [comment]
> I can connect to the camera (Phantom Veo410L) by camera.connect(), but in the get_single_frame.py I get
> 
> ```
> Traceback (most recent call last):
>   File "get_single_frame.py", line 22, in <module>
>     get_single_frame(take_number=0, frame_number=0)
>   File "get_single_frame.py", line 15, in get_single_frame
>     frame_index = int(camera.takes[take_number]["firstfr"]) + frame_number
>   File "/home/tim/.local/lib/python3.8/site-packages/pyphantom/flex.py", line 458, in __getitem__
>     raise IndexError
> IndexError
> ```
> 
> since camera.takes is empty. How can I start a recording using the pyphantom framework? I found the toggle() function in flex.py, which makes the cameras red led blink. When I now execute get_frames(), I get the error: `CameraError: Cinemag not ready` So how can I get frames from the camera?

Have you fixed the IndexError yet? Can you help me?
